### PR TITLE
ABS - first featured datasets to go up

### PR DESCRIPTION
**Pull request by chris-beer**
Will be some updates to these later as URI's etc firm up.

### CODE REVIEW

**Comment by keithamoss** [comment]
Wonderful, thanks Chris!

Does it make sense to list you as mentor for the ABS dataportal entry?

**Comment by chris-beer** [comment]
Yep it does. Oh - and the "portal" dataset entry (govhack.abs.gov.au + our
slack channel etc) btw will come last after our people here work out the
featured datasets finally (cause the portal is "everything else").

Any chance I can get write/merge access so I don't keep hassling you guys
(and can help as you need?)

Cheers

C.

**Comment by keithamoss** [comment]
Absolutely - you should have an invite w/ write access now :)

In a much broader sense I'd be interested in your thoughts around how we're making datasets/data portals and mentors discoverable on the portal. Anything we could do to improve et cetera.

**Comment by chris-beer** [comment]
Updates to ABS (datasets et. al) only

**Pull request merged**
